version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres      # Установи имя пользователя для базы данных
      POSTGRES_PASSWORD: admin     # Установи пароль для базы данных
      POSTGRES_DB: mydb            # Установи имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные базы данных на диск
      - ./initdb:/docker-entrypoint-initdb.d  # Монтирование папки с SQL-скриптами
    ports:
      - "5432:5432"  # Открываем порт для подключения к базе данных

  app:
    image: tomcat:10.1.24
    container_name: tomcat_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./target/TennisScoreboard-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war  # Копируем war файл в контейнер
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydb  # Используем db вместо localhost
      - DB_USER=postgres  # Имя пользователя базы данных
      - DB_PASSWORD=admin  # Пароль от базы данных

volumes:
  postgres_data:
    driver: local